### ISSUE TITLE
Postman tests running against localhost only and not Netlify preview deploy

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-subscriptions#23]
**Describe the bug**
CI flow has a bug. It waits for netlify preview deployment, but does not use it for test run.

https://github.com/ambianic/ambianic-subscriptions/blob/3d9c15b39721ee426f8141ba0bc57992e27fa09c/.github/workflows/ci.yml#L34

```
      - name: Wait for successful preview deployment
        if: ${{ github.event_name == 'pull_request' }}
        uses: jakepartusch/wait-for-netlify-action@v1
        id: get-netlify-url
        with:
          site_name: "ambianic-serverless"
          max_timeout: 60

      - name: Run tests against deployed preview
        if: ${{ github.event_name == 'pull_request' }}
        run:  npm run test:postman
        env:
          FUNCTION_URL: http://127.0.0.1:4010

```

**Expected behavior**
Inspect closely the ambianc-ui flow to understand how netlify wait assigns an environment variable which is then passed on to the test step.
https://github.com/ambianic/ambianic-subscriptions/blob/3d9c15b39721ee426f8141ba0bc57992e27fa09c/.github/workflows/ci.yml#L46
